export const initialHeroForm = {
  name: '',
  alias: '',
  role: '',
  power: '',
  description: '',
  image: '',
  imagePublicId: '',
  city: 'Gotham',
  mapPoint: null,
}

export const initialCriminalForm = {
  name: '',
  alias: '',
  crimeType: '',
  zone: 'Gotham',
  description: '',
  image: '',
  imagePublicId: '',
  threatLevel: 'Medium',
  mapPoint: null,
}

export const threatColors = {
  Low: 'success',
  Medium: 'processing',
  High: 'warning',
  Extreme: 'error',
}

export const fallbackCarouselItems = [
  {
    key: 'fallback-batman',
    type: 'Hero',
    alias: 'Batman',
    name: 'Bruce Wayne',
    image: '/images/4k-01.jpg',
    metaPrimary: 'Detective',
    metaSecondary: 'Tactical surveillance',
  },
  {
    key: 'fallback-catwoman',
    type: 'Villain',
    alias: 'Catwoman',
    name: 'Selina Kyle',
    image: '/images/4k-02.jpg',
    metaPrimary: 'Master thief',
    metaSecondary: 'High agility',
  },
  {
    key: 'fallback-nightwing',
    type: 'Hero',
    alias: 'Nightwing',
    name: 'Dick Grayson',
    image: '/images/4k-03.jpg',
    metaPrimary: 'Field leader',
    metaSecondary: 'Acrobatic combat',
  },
  {
    key: 'fallback-joker',
    type: 'Villain',
    alias: 'Joker',
    name: 'Unknown',
    image: '/images/4k-04.jpg',
    metaPrimary: 'Chaos operator',
    metaSecondary: 'Extreme threat',
  },
  {
    key: 'fallback-robin',
    type: 'Hero',
    alias: 'Robin',
    name: 'Damian Wayne',
    image: '/images/4k-05.jpg',
    metaPrimary: 'Close-quarters specialist',
    metaSecondary: 'Rapid response',
  },
  {
    key: 'fallback-harley',
    type: 'Villain',
    alias: 'Harley Quinn',
    name: 'Harleen Quinzel',
    image: '/images/1.jpeg',
    metaPrimary: 'Wildcard operative',
    metaSecondary: 'Unstable tactics',
  },
  {
    key: 'fallback-batgirl',
    type: 'Hero',
    alias: 'Batgirl',
    name: 'Barbara Gordon',
    image: '/images/2.jpeg',
    metaPrimary: 'Intel specialist',
    metaSecondary: 'Network defense',
  },
  {
    key: 'fallback-penguin',
    type: 'Villain',
    alias: 'Penguin',
    name: 'Oswald Cobblepot',
    image: '/images/3.jpeg',
    metaPrimary: 'Crime boss',
    metaSecondary: 'Underworld influence',
  },
  {
    key: 'fallback-redhood',
    type: 'Hero',
    alias: 'Red Hood',
    name: 'Jason Todd',
    image: '/images/4.jpeg',
    metaPrimary: 'Tactical striker',
    metaSecondary: 'High-risk pursuit',
  },
  {
    key: 'fallback-riddler',
    type: 'Villain',
    alias: 'Riddler',
    name: 'Edward Nygma',
    image: '/images/5.jpeg',
    metaPrimary: 'Puzzle architect',
    metaSecondary: 'Cognitive threat',
  },
  {
    key: 'fallback-alfred',
    type: 'Hero',
    alias: 'Alfred',
    name: 'Alfred Pennyworth',
    image: '/images/6.jpeg',
    metaPrimary: 'Operations control',
    metaSecondary: 'Mission support',
  },
  {
    key: 'fallback-freeze',
    type: 'Villain',
    alias: 'Mr. Freeze',
    name: 'Victor Fries',
    image: '/images/7.jpeg',
    metaPrimary: 'Cryo weaponry',
    metaSecondary: 'Cold-zone hazard',
  },
  {
    key: 'fallback-oracle',
    type: 'Hero',
    alias: 'Oracle',
    name: 'Barbara Gordon',
    image: '/images/8.jpeg',
    metaPrimary: 'Remote overwatch',
    metaSecondary: 'Signals command',
  },
  {
    key: 'fallback-ivy',
    type: 'Villain',
    alias: 'Poison Ivy',
    name: 'Pamela Isley',
    image: '/images/9.jpeg',
    metaPrimary: 'Biochemical control',
    metaSecondary: 'Environmental threat',
  },
  {
    key: 'fallback-lucius',
    type: 'Hero',
    alias: 'Lucius Fox',
    name: 'Lucius Fox',
    image: '/images/10.jpeg',
    metaPrimary: 'Tech systems',
    metaSecondary: 'Equipment pipeline',
  },
  {
    key: 'fallback-bane',
    type: 'Villain',
    alias: 'Bane',
    name: 'Unknown',
    image: '/images/4k-05.jpg',
    metaPrimary: 'Siege breaker',
    metaSecondary: 'Extreme force',
  },
  {
    key: 'fallback-huntress',
    type: 'Hero',
    alias: 'Huntress',
    name: 'Helena Bertinelli',
    image: '/images/1.jpeg',
    metaPrimary: 'Pursuit specialist',
    metaSecondary: 'Precision strike',
  },
  {
    key: 'fallback-twoface',
    type: 'Villain',
    alias: 'Two-Face',
    name: 'Harvey Dent',
    image: '/images/2.jpeg',
    metaPrimary: 'Dual-pattern threat',
    metaSecondary: 'Organized crime',
  },
  {
    key: 'fallback-azrael',
    type: 'Hero',
    alias: 'Azrael',
    name: 'Jean-Paul Valley',
    image: '/images/3.jpeg',
    metaPrimary: 'Heavy response',
    metaSecondary: 'Close assault',
  },
  {
    key: 'fallback-scarecrow',
    type: 'Villain',
    alias: 'Scarecrow',
    name: 'Jonathan Crane',
    image: '/images/4.jpeg',
    metaPrimary: 'Fear toxin',
    metaSecondary: 'Psychological warfare',
  },
]

export const pageTitleMap = {
  home: 'Home',
  map: 'Map',
  dashboard: 'Dashboard',
  heroes: 'Hero Management',
  criminals: 'Criminal Management',
}
